### ISSUE TITLE
buffer_not_empty condition

### ISSUE THREAD

**Issue by pettni** [NTBBloodbath/galaxyline.nvim#11]
Thanks for picking up the baton on this.

I saw some unexpected behavior and noticed that this function might be doing the opposite of what I expected from the readme.

https://github.com/NTBBloodbath/galaxyline.nvim/blob/9e0a3a20633fdfedc8662a2ff370944d65c30836/lua/galaxyline/condition.lua#L3-L6

**Comment by NTBBloodbath** [comment]
Hey, yeah I already fixed this (it seems that I forgot to push haha), please update and feel free to reopen this issue if you're still facing this error after the update.

Regards
