### ISSUE TITLE
Downside of using gitsigns variables directly

### ISSUE THREAD

**Issue by mks1508** [NTBBloodbath/galaxyline.nvim#4]
If git repo is just been initialized and have no commit, `b:gitsigns_head` will still exist but with value `""`
So should we use something like:
```lua
local function is_empty(something)
  return something == nil or something == ""
end

if is_empty(vim.b.gitsigns_head) then
  return
end
```
Instead of `vim.fn.exists("b:gitsigns_head")`

**Comment by NTBBloodbath** [comment]
Hi, thank you for pointing this (haven't tried with new repositories, only existing ones). I'll fix it asap :slightly_smiling_face:
