### ISSUE TITLE
Is LSP provider global or for the current buffer?

### ISSUE THREAD

**Issue by davidsierradz** [NTBBloodbath/galaxyline.nvim#9]
`vim.lsp.get_active_clients()` list all lsp clients even if they are not attached to the current buffer. I guess `vim.lsp.buf_get_clients()` is more accurate?

**Comment by NTBBloodbath** [comment]
Hey, thank you so much, I think this makes a lot more sense. I'll change it asap!

Regards

**Comment by davidsierradz** [comment]
Thanks! Sorry to bother you, but I think we should use `pairs` instead of `ipairs` because `buf_get_clients` does not necessarily return a contiguous list-like table. See [fix(lsp): avoid ipairs on non-sequential tables by mjlbach · Pull Request #15059 · neovim/neovim](https://github.com/neovim/neovim/pull/15059).

**Comment by NTBBloodbath** [comment]
Don't worry haha you're not bothering me :)

Didn't know about this, I'll change it very quickly and commit, thank you for pointing this!
